name: e2e
on:
  pull_request:
  push:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: |
          pnpm start &
          sleep 5
      - run: pnpm exec playwright install --with-deps
      - run: pnpm exec playwright test
